FROM nginx:latest
#this will add a new layer
RUN echo '<h1>hello</h1>' > /usr/share/nginx/html/index.html
#run: docker image build -t ex-simple-build
#run docker image ls
#see the image
#run container: docker container run -p 80:80 ex-simple-build
#open localhost